[package]
name = "stdin-tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
portal-puncher-sm = { path = "../portal-puncher-sm", version = "0.1.0-beta.0" }
